//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.smellyriver.com/TankInspector/Data/Tank.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.smellyriver.com/TankInspector/Data/Tank.xsd", IsNullable=false)]
public partial class tank {
    
    private tankCrew[] crewField;
    
    private string keyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("crew", IsNullable=false)]
    public tankCrew[] crew {
        get {
            return this.crewField;
        }
        set {
            this.crewField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.smellyriver.com/TankInspector/Data/Tank.xsd")]
public partial class tankCrew {
    
    private string secondaryRolesField;
    
    private CrewRole[] roleField;
    
    /// <remarks/>
    public string secondaryRoles {
        get {
            return this.secondaryRolesField;
        }
        set {
            this.secondaryRolesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public CrewRole[] role {
        get {
            return this.roleField;
        }
        set {
            this.roleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.smellyriver.com/TankInspector/Data/Common.xsd")]
public enum CrewRole {
    
    /// <remarks/>
    commander,
    
    /// <remarks/>
    driver,
    
    /// <remarks/>
    gunner,
    
    /// <remarks/>
    loader,
    
    /// <remarks/>
    radioman,
}
