using System.Collections.Generic;
using Smellyriver.TankInspector.Pro.Data.Stats;

namespace Smellyriver.TankInspector.Pro.LivestatProvider
{
    class LivestatProvider : IStatsProvider
    {
        private readonly Livestat[] _stats;

        public IEnumerable<IStat> Stats
        {
            get { return _stats; }
        }

        public LivestatProvider()
        {
            _stats = new[]
            {
                             
                new Livestat("livestat_damageDealt",
                             i => i.vbaddict.damage_dealt,
                             new[]{ "#livestats:category_livestat", "#stats:category_firepower"},
                             "#livestats:damage_dealt",
                             "#livestats:damage_dealt_short_name",
                             "#livestats:damage_dealt_description",
                             null,
                             BenchmarkThreshold.Default,
                             CompareStrategy.HigherBetter,
                             "{0:#,0.#}"),
                new Livestat("livestat_potentialDamageReceived",
                             i => i.vbaddict.potential_damage_received,
                             new[]{ "#livestats:category_livestat", "#stats:category_survivability"},
                             "#livestats:potential_damage_received",
                             "#livestats:potential_damage_received_short_name",
                             "#livestats:potential_damage_received_description",
                             null,
                             BenchmarkThreshold.Default,
                             CompareStrategy.Plain,
                             "{0:#,0.#}"),
                new Livestat("livestat_damageReceived",
                             i => i.vbaddict.damage_received,
                             new[]{ "#livestats:category_livestat", "#stats:category_survivability"},
                             "#livestats:damage_received",
                             "#livestats:damage_received_short_name",
                             "#livestats:damage_received_description",
                             null,
                             BenchmarkThreshold.Default,
                             CompareStrategy.Plain,
                             "{0:#,0.#}"),
                new Livestat("livestat_damageAssistedRadio",
                             i => i.vbaddict.damage_assisted_radio,
                             new[]{ "#livestats:category_livestat", "#stats:category_scoutability"},
                             "#livestats:damage_assisted_radio",
                             "#livestats:damage_assisted_radio_short_name",
                             "#livestats:damage_assisted_radio_description",
                             null,
                             BenchmarkThreshold.Default,
                             CompareStrategy.HigherBetter,
                             "{0:#,0.#}"),
                new Livestat("livestat_damageAssistedTrack",
                             i => i.vbaddict.damage_assisted_track,
                             new[]{ "#livestats:category_livestat", "#stats:category_scoutability"},
                             "#livestats:damage_assisted_track",
                             "#livestats:damage_assisted_track_short_name",
                             "#livestats:damage_assisted_track_description",
                             null,
                             BenchmarkThreshold.Default,
                             CompareStrategy.HigherBetter,
                             "{0:#,0.#}"),
                new Livestat("livestat_accuracy",
                             i => i.vbaddict.accuracy,
                             new[]{ "#livestats:category_livestat", "#stats:category_maneuverability"},
                             "#livestats:accuracy",
                             "#livestats:accuracy_short_name",
                             "#livestats:accuracy_description",
                             null,
                             BenchmarkThreshold.Default,
                             CompareStrategy.HigherBetter,
                             "{0:#,0.#}%"),
                new Livestat("livestat_experience",
                             i => i.vbaddict.experience,
                             new[]{ "#livestats:category_livestat", "#stats:category_economy"},
                             "#livestats:experience",
                             "#livestats:experience_short_name",
                             "#livestats:experience_description",
                             null,
                             BenchmarkThreshold.Default,
                             CompareStrategy.HigherBetter,
                             "{0:#,0.#}"),
                new Livestat("livestat_creditsb",
                             i => i.vbaddict.creditsb,
                             new[]{ "#livestats:category_livestat", "#stats:category_economy"},
                             "#livestats:credits_bulk",
                             "#livestats:credits_bulk_short_name",
                             "#livestats:credits_bulk_description",
                             "#stats:unit_credits",
                             BenchmarkThreshold.Default,
                             CompareStrategy.HigherBetter,
                             "{0:#,0.#}"),
                new Livestat("livestat_operatingCosts",
                             i => i.vbaddict.operating_costs,
                             new[]{ "#livestats:category_livestat", "#stats:category_economy"},
                             "#livestats:operating_costs",
                             "#livestats:operating_costs_short_name",
                             "#livestats:operating_costs_description",
                             "#stats:unit_credits",
                             BenchmarkThreshold.Default,
                             CompareStrategy.LowerBetter,
                             "{0:#,0.#}"),
                new Livestat("livestat_equipCosts",
                             i => i.vbaddict.equip_costs,
                             new[]{ "#livestats:category_livestat", "#stats:category_economy"},
                             "#livestats:equipment_costs",
                             "#livestats:equipment_costs_short_name",
                             "#livestats:equipment_costs_description",
                             "#stats:unit_credits",
                             BenchmarkThreshold.Default,
                             CompareStrategy.LowerBetter,
                             "{0:#,0.#}"),
                new Livestat("livestat_ammunitionCosts",
                             i => i.vbaddict.ammunition_costs,
                             new[]{ "#livestats:category_livestat", "#stats:category_economy"},
                             "#livestats:ammunition_costs",
                             "#livestats:ammunition_costs_short_name",
                             "#livestats:ammunition_costs_description",
                             "#stats:unit_credits",
                             BenchmarkThreshold.Default,
                             CompareStrategy.LowerBetter,
                             "{0:#,0.#}"),
                new Livestat("livestat_repairCosts",
                             i => i.vbaddict.repair_costs,
                             new[]{ "#livestats:category_livestat", "#stats:category_economy"},
                             "#livestats:repair_costs",
                             "#livestats:repair_costs_short_name",
                             "#livestats:repair_costs_description",
                             "#stats:unit_credits",
                             BenchmarkThreshold.Default,
                             CompareStrategy.LowerBetter,
                             "{0:#,0.#}"),
                new Livestat("livestat_creditsn",
                             i => i.vbaddict.creditsn,
                             new[]{ "#livestats:category_livestat", "#stats:category_economy"},
                             "#livestats:credits_net",
                             "#livestats:credits_net_short_name",
                             "#livestats:credits_net_description",
                             "#stats:unit_credits",
                             BenchmarkThreshold.Default,
                             CompareStrategy.HigherBetter,
                             "{0:#,0.#}"),
                new Livestat("livestat_mileage",
                             i => i.vbaddict.mileage,
                             new[]{ "#livestats:category_livestat", "#stats:category_mobility"},
                             "#livestats:mileage",
                             "#livestats:mileage_short_name",
                             "#livestats:mileage_description",
                             "#stats:unit_meters",
                             BenchmarkThreshold.Default,
                             CompareStrategy.Plain,
                             "{0:#,0.#}"),
                new Livestat("livestat_spotted",
                             i => i.vbaddict.spotted,
                             new[]{ "#livestats:category_livestat", "#stats:category_scoutability"},
                             "#livestats:spotted",
                             "#livestats:spotted_short_name",
                             "#livestats:spotted_description",
                             null,
                             BenchmarkThreshold.Default,
                             CompareStrategy.HigherBetter,
                             "{0:#,0.#}"),
                new Livestat("livestat_winrate",
                             i => i.vbaddict.winrate,
                             new[]{ "#livestats:category_livestat", "#stats:category_combat"},
                             "#livestats:winrate",
                             "#livestats:winrate_short_name",
                             "#livestats:winrate_description",
                             null,
                             BenchmarkThreshold.Default,
                             CompareStrategy.HigherBetter,
                             "{0:#,0.#}%"),
                new Livestat("livestat_damaged",
                             i => i.vbaddict.damaged,
                             new[]{ "#livestats:category_livestat", "#stats:category_combat"},
                             "#livestats:damaged",
                             "#livestats:damaged_short_name",
                             "#livestats:damaged_description",
                             null,
                             BenchmarkThreshold.Default,
                             CompareStrategy.HigherBetter,
                             "{0:#,0.#}"),
                new Livestat("livestat_efficiency_wnx",
                             i => i.vbaddict.efficiency_wnx,
                             new[]{ "#livestats:category_livestat", "#stats:category_combat"},
                             "#livestats:efficiency_wnx",
                             "#livestats:efficiency_wnx_short_name",
                             "#livestats:efficiency_wnx_description",
                             null,
                             BenchmarkThreshold.Default,
                             CompareStrategy.HigherBetter,
                             "{0:#,0.#}"),
                new Livestat("livestat_efficiency_wn7",
                             i => i.vbaddict.efficiency_wn7,
                             new[]{ "#livestats:category_livestat", "#stats:category_combat"},
                             "#livestats:efficiency_wn7",
                             "#livestats:efficiency_wn7_short_name",
                             "#livestats:efficiency_wn7_description",
                             null,
                             BenchmarkThreshold.Default,
                             CompareStrategy.HigherBetter,
                             "{0:#,0.#}"),
                new Livestat("livestat_efficiency_wn8",
                             i => i.vbaddict.efficiency_wn8,
                             new[]{ "#livestats:category_livestat", "#stats:category_combat"},
                             "#livestats:efficiency_wn8",
                             "#livestats:efficiency_wn8_short_name",
                             "#livestats:efficiency_wn8_description",
                             null,
                             BenchmarkThreshold.Default,
                             CompareStrategy.HigherBetter,
                             "{0:#,0.#}"),
                new Livestat("livestat_efficiency_box",
                             i => i.vbaddict.efficiency_box,
                             new[]{ "#livestats:category_livestat", "#stats:category_combat"},
                             "#livestats:efficiency_box",
                             "#livestats:efficiency_box_short_name",
                             "#livestats:efficiency_box_description",
                             null,
                             BenchmarkThreshold.Default,
                             CompareStrategy.HigherBetter,
                             "{0:#,0.#}"),
                new Livestat("livestat_killed",
                             i => i.vbaddict.killed,
                             new[]{ "#livestats:category_livestat", "#stats:category_combat"},
                             "#livestats:killed",
                             "#livestats:killed_short_name",
                             "#livestats:killed_description",
                             null,
                             BenchmarkThreshold.Default,
                             CompareStrategy.HigherBetter,
                             "{0:#,0.#}"),
                new Livestat("livestat_battleTime",
                             i => i.vbaddict.battle_time,
                             new[]{ "#livestats:category_livestat", "#stats:category_combat"},
                             "#livestats:battle_time",
                             "#livestats:battle_time_short_name",
                             "#livestats:battle_time_description",
                             "#livestats:unit_minutes",
                             BenchmarkThreshold.Default,
                             CompareStrategy.HigherBetter,
                             "{0:#,0.#}"),
                new Livestat("livestat_survived",
                             i => i.vbaddict.survived,
                             new[]{ "#livestats:category_livestat", "#stats:category_survivability"},
                             "#livestats:survived",
                             "#livestats:survived_short_name",
                             "#livestats:survived_description",
                             null,
                             BenchmarkThreshold.Default,
                             CompareStrategy.HigherBetter,
                             "{0:#,0.#}%"),
                new Livestat("livestat_frequencyOfOccurrence",
                             i => i.vbaddict.frequency_of_occurrence,
                             new[]{ "#livestats:category_livestat", "#stats:category_combat"},
                             "#livestats:frequency_of_occurrence",
                             "#livestats:frequency_of_occurrence_short_name",
                             "#livestats:frequency_of_occurrence_description",
                             null,
                             BenchmarkThreshold.Default,
                             CompareStrategy.Plain,
                             "{0:#,0}"),
                new Livestat("livestat_experiencePerMinute",
                             i => i.vbaddict.experience_per_minute,
                             new[]{ "#livestats:category_livestat", "#stats:category_economy"},
                             "#livestats:experience_per_minute",
                             "#livestats:experience_per_minute_short_name",
                             "#livestats:experience_per_minute_description",
                             "#livestats:unit_xp_per_minute",
                             BenchmarkThreshold.Default,
                             CompareStrategy.HigherBetter,
                             "{0:#,0.#}"),
                new Livestat("livestat_penetrationRate",
                             i => i.vbaddict.penetration_rate,
                             new[]{ "#livestats:category_livestat", "#stats:category_firepower"},
                             "#livestats:penetration_rate",
                             "#livestats:penetration_rate_short_name",
                             "#livestats:penetration_rate_description",
                             null,
                             BenchmarkThreshold.Default,
                             CompareStrategy.HigherBetter,
                             "{0:#,0.#}%"),
                new Livestat("livestat_noDamageShotsRatio",
                             i => i.vbaddict.nodamageshotsratio,
                             new[]{ "#livestats:category_livestat", "#stats:category_firepower"},
                             "#livestats:no_damage_shots_ratio",
                             "#livestats:no_damage_shots_ratio_short_name",
                             "#livestats:no_damage_shots_ratio_description",
                             null,
                             BenchmarkThreshold.Default,
                             CompareStrategy.HigherBetter,
                             "{0:#,0.#}%"),
                new Livestat("livestat_kamikaze",
                             i => i.vbaddict.kamikaze,
                             new[]{ "#livestats:category_livestat", "#stats:category_combat"},
                             "#livestats:kamikaze",
                             "#livestats:kamikaze_short_name",
                             "#livestats:kamikaze_description",
                             null,
                             BenchmarkThreshold.Default,
                             CompareStrategy.LowerBetter,
                             "{0:#,0.#}%"),
                new Livestat("livestat_sleeping",
                             i => i.vbaddict.sleeping,
                             new[]{ "#livestats:category_livestat", "#stats:category_combat"},
                             "#livestats:sleeping",
                             "#livestats:sleeping_short_name",
                             "#livestats:sleeping_description",
                             null,
                             BenchmarkThreshold.Default,
                             CompareStrategy.LowerBetter,
                             "{0:#,0.#}%"),
                new Livestat("livestat_mmTierWeight",
                             i => i.vbaddict.mm_tier_weight,
                             new[]{ "#livestats:category_livestat", "#stats:category_combat"},
                             "#livestats:mm_tier_weight",
                             "#livestats:mm_tier_weight_short_name",
                             "#livestats:mm_tier_weight_description",
                             null,
                             BenchmarkThreshold.Default,
                             CompareStrategy.LowerBetter,
                             "{0:#,0.#}"),
            };
        }
    }
}
