//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Media;

namespace Smellyriver.TankInspector.Pro.ModelShared {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ModelSharedSettings : ApplicationSettingsBase {
        
        private static ModelSharedSettings defaultInstance = ((ModelSharedSettings)(ApplicationSettingsBase.Synchronized(new ModelSharedSettings())));
        
        public static ModelSharedSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("128")]
        public int MinimumStaticOutputWidth {
            get {
                return ((int)(this["MinimumStaticOutputWidth"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("128")]
        public int MinimumStaticOutputHeight {
            get {
                return ((int)(this["MinimumStaticOutputHeight"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("4096")]
        public int MaximumStaticOutputWidth {
            get {
                return ((int)(this["MaximumStaticOutputWidth"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("4096")]
        public int MaximumStaticOutputHeight {
            get {
                return ((int)(this["MaximumStaticOutputHeight"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("128")]
        public int MinimumAnimationOutputWidth {
            get {
                return ((int)(this["MinimumAnimationOutputWidth"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("128")]
        public int MinimumAnimationOutputHeight {
            get {
                return ((int)(this["MinimumAnimationOutputHeight"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1024")]
        public int MaximumAnimationOutputWidth {
            get {
                return ((int)(this["MaximumAnimationOutputWidth"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1024")]
        public int MaximumAnimationOutputHeight {
            get {
                return ((int)(this["MaximumAnimationOutputHeight"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public int MinimumAnimationFramerate {
            get {
                return ((int)(this["MinimumAnimationFramerate"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("30")]
        public int MaximumAnimationFramerate {
            get {
                return ((int)(this["MaximumAnimationFramerate"]));
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("24")]
        public int AnimationFramerate {
            get {
                return ((int)(this["AnimationFramerate"]));
            }
            set {
                this["AnimationFramerate"] = value;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1920")]
        public int DefaultStaticOutputWidth {
            get {
                return ((int)(this["DefaultStaticOutputWidth"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1080")]
        public int DefaultStaticOutputHeight {
            get {
                return ((int)(this["DefaultStaticOutputHeight"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("400")]
        public int DefaultAnimationOutputWidth {
            get {
                return ((int)(this["DefaultAnimationOutputWidth"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("300")]
        public int DefaultAnimationOutputHeight {
            get {
                return ((int)(this["DefaultAnimationOutputHeight"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("24")]
        public int DefaultAnimationFramerate {
            get {
                return ((int)(this["DefaultAnimationFramerate"]));
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFFFFFFF")]
        public Color ShadeColor {
            get {
                return ((Color)(this["ShadeColor"]));
            }
            set {
                this["ShadeColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0.1,0.1,0.8,0.8")]
        public Rect ClippingRatioRectangle {
            get {
                return ((Rect)(this["ClippingRatioRectangle"]));
            }
            set {
                this["ClippingRatioRectangle"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("2")]
        public double StaticCaptureSampleFactor {
            get {
                return ((double)(this["StaticCaptureSampleFactor"]));
            }
            set {
                this["StaticCaptureSampleFactor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1")]
        public double AnimationSampleFactor {
            get {
                return ((double)(this["AnimationSampleFactor"]));
            }
            set {
                this["AnimationSampleFactor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool EnableAnimationPreview {
            get {
                return ((bool)(this["EnableAnimationPreview"]));
            }
            set {
                this["EnableAnimationPreview"] = value;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("3")]
        public double MaximumModelComparerInterval {
            get {
                return ((double)(this["MaximumModelComparerInterval"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0.1")]
        public double MinimumModelComparerInterval {
            get {
                return ((double)(this["MinimumModelComparerInterval"]));
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1.5")]
        public double ModelComparerInterval {
            get {
                return ((double)(this["ModelComparerInterval"]));
            }
            set {
                this["ModelComparerInterval"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool PrintVersionOnModelComparer {
            get {
                return ((bool)(this["PrintVersionOnModelComparer"]));
            }
            set {
                this["PrintVersionOnModelComparer"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string OutputDirectory {
            get {
                return ((string)(this["OutputDirectory"]));
            }
            set {
                this["OutputDirectory"] = value;
            }
        }
    }
}
