//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using Smellyriver.TankInspector.Pro.Data.Stats;

namespace Smellyriver.TankInspector.Pro.StatComparer {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class StatComparerSettings : ApplicationSettingsBase {
        
        private static StatComparerSettings defaultInstance = ((StatComparerSettings)(ApplicationSettingsBase.Synchronized(new StatComparerSettings())));
        
        public static StatComparerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Instance")]
        public StatValueMode StatValueMode {
            get {
                return ((StatValueMode)(this["StatValueMode"]));
            }
            set {
                this["StatValueMode"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int ColumnMode {
            get {
                return ((int)(this["ColumnMode"]));
            }
            set {
                this["ColumnMode"] = value;
            }
        }
    }
}
