//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Smellyriver.TankInspector.Pro {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ApplicationState : ApplicationSettingsBase {
        
        private static ApplicationState defaultInstance = ((ApplicationState)(ApplicationSettingsBase.Synchronized(new ApplicationState())));
        
        public static ApplicationState Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string PreviousLoginToken {
            get {
                return ((string)(this["PreviousLoginToken"]));
            }
            set {
                this["PreviousLoginToken"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public long PreviousLoginTime {
            get {
                return ((long)(this["PreviousLoginTime"]));
            }
            set {
                this["PreviousLoginTime"] = value;
            }
        }
    }
}
