//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Smellyriver.TankInspector.Pro {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class DebugSettings : ApplicationSettingsBase {
        
        private static DebugSettings defaultInstance = ((DebugSettings)(ApplicationSettingsBase.Synchronized(new DebugSettings())));
        
        public static DebugSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool EnableXPathStatDebug {
            get {
                return ((bool)(this["EnableXPathStatDebug"]));
            }
            set {
                this["EnableXPathStatDebug"] = value;
            }
        }
    }
}
