//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Smellyriver.TankInspector.Pro {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ModelSettings : ApplicationSettingsBase {
        
        private static ModelSettings defaultInstance = ((ModelSettings)(ApplicationSettingsBase.Synchronized(new ModelSettings())));
        
        public static ModelSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int ModelType {
            get {
                return ((int)(this["ModelType"]));
            }
            set {
                this["ModelType"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool UseHDModel {
            get {
                return ((bool)(this["UseHDModel"]));
            }
            set {
                this["UseHDModel"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool WireframeMode {
            get {
                return ((bool)(this["WireframeMode"]));
            }
            set {
                this["WireframeMode"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool ShowChassis {
            get {
                return ((bool)(this["ShowChassis"]));
            }
            set {
                this["ShowChassis"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool ShowHull {
            get {
                return ((bool)(this["ShowHull"]));
            }
            set {
                this["ShowHull"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool ShowTurret {
            get {
                return ((bool)(this["ShowTurret"]));
            }
            set {
                this["ShowTurret"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool ShowGun {
            get {
                return ((bool)(this["ShowGun"]));
            }
            set {
                this["ShowGun"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool GridTextureMode {
            get {
                return ((bool)(this["GridTextureMode"]));
            }
            set {
                this["GridTextureMode"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool UseModTexture {
            get {
                return ((bool)(this["UseModTexture"]));
            }
            set {
                this["UseModTexture"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool ShowCamouflage {
            get {
                return ((bool)(this["ShowCamouflage"]));
            }
            set {
                this["ShowCamouflage"] = value;
            }
        }
    }
}
