//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Smellyriver.TankInspector.Pro.ModelInspector {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ModelInspectorSettings : ApplicationSettingsBase {
        
        private static ModelInspectorSettings defaultInstance = ((ModelInspectorSettings)(ApplicationSettingsBase.Synchronized(new ModelInspectorSettings())));
        
        public static ModelInspectorSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("360")]
        public double MaximumRotationSpeed {
            get {
                return ((double)(this["MaximumRotationSpeed"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1")]
        public double MinimumRotationSpeed {
            get {
                return ((double)(this["MinimumRotationSpeed"]));
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("270")]
        public double RotationSpeed {
            get {
                return ((double)(this["RotationSpeed"]));
            }
            set {
                this["RotationSpeed"] = value;
            }
        }
    }
}
