//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Smellyriver.TankInspector.Pro.TankMuseum {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class TankMuseumSettings : ApplicationSettingsBase {
        
        private static TankMuseumSettings defaultInstance = ((TankMuseumSettings)(ApplicationSettingsBase.Synchronized(new TankMuseumSettings())));
        
        public static TankMuseumSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int FilterMode {
            get {
                return ((int)(this["FilterMode"]));
            }
            set {
                this["FilterMode"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("all")]
        public string NationFilter {
            get {
                return ((string)(this["NationFilter"]));
            }
            set {
                this["NationFilter"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("all")]
        public string ClassFilter {
            get {
                return ((string)(this["ClassFilter"]));
            }
            set {
                this["ClassFilter"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int TierFilter {
            get {
                return ((int)(this["TierFilter"]));
            }
            set {
                this["TierFilter"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int PremiumFilter {
            get {
                return ((int)(this["PremiumFilter"]));
            }
            set {
                this["PremiumFilter"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("all")]
        public string RepositoryFilter {
            get {
                return ((string)(this["RepositoryFilter"]));
            }
            set {
                this["RepositoryFilter"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string FilterKeyword {
            get {
                return ((string)(this["FilterKeyword"]));
            }
            set {
                this["FilterKeyword"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool IgnoreSpacesAndDashes {
            get {
                return ((bool)(this["IgnoreSpacesAndDashes"]));
            }
            set {
                this["IgnoreSpacesAndDashes"] = value;
            }
        }
    }
}
