//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Smellyriver.TankInspector.Pro.CrewConfigurator {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class CrewConfiguratorSettings : ApplicationSettingsBase {
        
        private static CrewConfiguratorSettings defaultInstance = ((CrewConfiguratorSettings)(ApplicationSettingsBase.Synchronized(new CrewConfiguratorSettings())));
        
        public static CrewConfiguratorSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool CommanderExpanded {
            get {
                return ((bool)(this["CommanderExpanded"]));
            }
            set {
                this["CommanderExpanded"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool DriverExpanded {
            get {
                return ((bool)(this["DriverExpanded"]));
            }
            set {
                this["DriverExpanded"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool Gunner1Expanded {
            get {
                return ((bool)(this["Gunner1Expanded"]));
            }
            set {
                this["Gunner1Expanded"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool Gunner2Expanded {
            get {
                return ((bool)(this["Gunner2Expanded"]));
            }
            set {
                this["Gunner2Expanded"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool Loader1Expanded {
            get {
                return ((bool)(this["Loader1Expanded"]));
            }
            set {
                this["Loader1Expanded"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool Loader2Expanded {
            get {
                return ((bool)(this["Loader2Expanded"]));
            }
            set {
                this["Loader2Expanded"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool Radioman1Expanded {
            get {
                return ((bool)(this["Radioman1Expanded"]));
            }
            set {
                this["Radioman1Expanded"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool Radioman2Expanded {
            get {
                return ((bool)(this["Radioman2Expanded"]));
            }
            set {
                this["Radioman2Expanded"] = value;
            }
        }
    }
}
