//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Runtime.CompilerServices;

namespace Smellyriver.TankInspector.Pro.ArmorInspector {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ArmorInspectorSettings : ApplicationSettingsBase {
        
        private static ArmorInspectorSettings defaultInstance = ((ArmorInspectorSettings)(ApplicationSettingsBase.Synchronized(new ArmorInspectorSettings())));
        
        public static ArmorInspectorSettings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
