//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Smellyriver.TankInspector.Pro.GameClientExplorer {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class GameClientExplorerSettings : ApplicationSettingsBase {
        
        private static GameClientExplorerSettings defaultInstance = ((GameClientExplorerSettings)(ApplicationSettingsBase.Synchronized(new GameClientExplorerSettings())));
        
        public static GameClientExplorerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int SortTanksBy {
            get {
                return ((int)(this["SortTanksBy"]));
            }
            set {
                this["SortTanksBy"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool SortTanksDescending {
            get {
                return ((bool)(this["SortTanksDescending"]));
            }
            set {
                this["SortTanksDescending"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool DeveloperMode {
            get {
                return ((bool)(this["DeveloperMode"]));
            }
            set {
                this["DeveloperMode"] = value;
            }
        }
    }
}
